//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.referenciaWs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsTimbradoSoap", Namespace="http://tempuri.org/")]
    public partial class wsTimbrado : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sellarOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarOperationCompleted;
        
        private System.Threading.SendOrPostCallback recuperarAcuseOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarAcuseCancelacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsTimbrado() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_referenciaWs_AutoComplete;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sellarCompletedEventHandler sellarCompleted;
        
        /// <remarks/>
        public event timbrarCompletedEventHandler timbrarCompleted;
        
        /// <remarks/>
        public event cancelarCompletedEventHandler cancelarCompleted;
        
        /// <remarks/>
        public event recuperarAcuseCompletedEventHandler recuperarAcuseCompleted;
        
        /// <remarks/>
        public event RecuperarAcuseCancelacionCompletedEventHandler RecuperarAcuseCancelacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sellar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultado sellar(string curCorreo, string password, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] KeyFile, string PassCsd, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] CerFile, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] xml) {
            object[] results = this.Invoke("sellar", new object[] {
                        curCorreo,
                        password,
                        KeyFile,
                        PassCsd,
                        CerFile,
                        xml});
            return ((resultado)(results[0]));
        }
        
        /// <remarks/>
        public void sellarAsync(string curCorreo, string password, byte[] KeyFile, string PassCsd, byte[] CerFile, byte[] xml) {
            this.sellarAsync(curCorreo, password, KeyFile, PassCsd, CerFile, xml, null);
        }
        
        /// <remarks/>
        public void sellarAsync(string curCorreo, string password, byte[] KeyFile, string PassCsd, byte[] CerFile, byte[] xml, object userState) {
            if ((this.sellarOperationCompleted == null)) {
                this.sellarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsellarOperationCompleted);
            }
            this.InvokeAsync("sellar", new object[] {
                        curCorreo,
                        password,
                        KeyFile,
                        PassCsd,
                        CerFile,
                        xml}, this.sellarOperationCompleted, userState);
        }
        
        private void OnsellarOperationCompleted(object arg) {
            if ((this.sellarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sellarCompleted(this, new sellarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/timbrar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultado timbrar(string curCorreo, string password, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] xml, bool pdf, string ambiente, string tipoTim, string conexion) {
            object[] results = this.Invoke("timbrar", new object[] {
                        curCorreo,
                        password,
                        xml,
                        pdf,
                        ambiente,
                        tipoTim,
                        conexion});
            return ((resultado)(results[0]));
        }
        
        /// <remarks/>
        public void timbrarAsync(string curCorreo, string password, byte[] xml, bool pdf, string ambiente, string tipoTim, string conexion) {
            this.timbrarAsync(curCorreo, password, xml, pdf, ambiente, tipoTim, conexion, null);
        }
        
        /// <remarks/>
        public void timbrarAsync(string curCorreo, string password, byte[] xml, bool pdf, string ambiente, string tipoTim, string conexion, object userState) {
            if ((this.timbrarOperationCompleted == null)) {
                this.timbrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbrarOperationCompleted);
            }
            this.InvokeAsync("timbrar", new object[] {
                        curCorreo,
                        password,
                        xml,
                        pdf,
                        ambiente,
                        tipoTim,
                        conexion}, this.timbrarOperationCompleted, userState);
        }
        
        private void OntimbrarOperationCompleted(object arg) {
            if ((this.timbrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbrarCompleted(this, new timbrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cancelar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultado cancelar(string curCorreo, string password, string[] UUID, string KeyEncode) {
            object[] results = this.Invoke("cancelar", new object[] {
                        curCorreo,
                        password,
                        UUID,
                        KeyEncode});
            return ((resultado)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarAsync(string curCorreo, string password, string[] UUID, string KeyEncode) {
            this.cancelarAsync(curCorreo, password, UUID, KeyEncode, null);
        }
        
        /// <remarks/>
        public void cancelarAsync(string curCorreo, string password, string[] UUID, string KeyEncode, object userState) {
            if ((this.cancelarOperationCompleted == null)) {
                this.cancelarOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarOperationCompleted);
            }
            this.InvokeAsync("cancelar", new object[] {
                        curCorreo,
                        password,
                        UUID,
                        KeyEncode}, this.cancelarOperationCompleted, userState);
        }
        
        private void OncancelarOperationCompleted(object arg) {
            if ((this.cancelarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarCompleted(this, new cancelarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/recuperarAcuse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultado recuperarAcuse(string curCorreo, string password, string UUID) {
            object[] results = this.Invoke("recuperarAcuse", new object[] {
                        curCorreo,
                        password,
                        UUID});
            return ((resultado)(results[0]));
        }
        
        /// <remarks/>
        public void recuperarAcuseAsync(string curCorreo, string password, string UUID) {
            this.recuperarAcuseAsync(curCorreo, password, UUID, null);
        }
        
        /// <remarks/>
        public void recuperarAcuseAsync(string curCorreo, string password, string UUID, object userState) {
            if ((this.recuperarAcuseOperationCompleted == null)) {
                this.recuperarAcuseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecuperarAcuseOperationCompleted);
            }
            this.InvokeAsync("recuperarAcuse", new object[] {
                        curCorreo,
                        password,
                        UUID}, this.recuperarAcuseOperationCompleted, userState);
        }
        
        private void OnrecuperarAcuseOperationCompleted(object arg) {
            if ((this.recuperarAcuseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recuperarAcuseCompleted(this, new recuperarAcuseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarAcuseCancelacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultado RecuperarAcuseCancelacion(string curCorreo, string password, string UUID) {
            object[] results = this.Invoke("RecuperarAcuseCancelacion", new object[] {
                        curCorreo,
                        password,
                        UUID});
            return ((resultado)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarAcuseCancelacionAsync(string curCorreo, string password, string UUID) {
            this.RecuperarAcuseCancelacionAsync(curCorreo, password, UUID, null);
        }
        
        /// <remarks/>
        public void RecuperarAcuseCancelacionAsync(string curCorreo, string password, string UUID, object userState) {
            if ((this.RecuperarAcuseCancelacionOperationCompleted == null)) {
                this.RecuperarAcuseCancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarAcuseCancelacionOperationCompleted);
            }
            this.InvokeAsync("RecuperarAcuseCancelacion", new object[] {
                        curCorreo,
                        password,
                        UUID}, this.RecuperarAcuseCancelacionOperationCompleted, userState);
        }
        
        private void OnRecuperarAcuseCancelacionOperationCompleted(object arg) {
            if ((this.RecuperarAcuseCancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarAcuseCancelacionCompleted(this, new RecuperarAcuseCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class resultado {
        
        private string selloField;
        
        private string erroresField;
        
        private byte[] xmlSelladoField;
        
        private byte[] acuseField;
        
        private wsItemCancelacionObj[] arrayFoliosField;
        
        private byte[][] arregloAcuseField;
        
        private string cadenaOriginalField;
        
        private System.DateTime fechaHoraTimbradoField;
        
        private bool fechaHoraTimbradoFieldSpecified;
        
        private bool fechaHoraTimbradoSpecified1Field;
        
        private string folioUUIDField;
        
        private byte[] pDFField;
        
        private string selloDigitalEmisorField;
        
        private string selloDigitalTimbreSATField;
        
        private byte[] xMLField;
        
        /// <remarks/>
        public string sello {
            get {
                return this.selloField;
            }
            set {
                this.selloField = value;
            }
        }
        
        /// <remarks/>
        public string errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] xmlSellado {
            get {
                return this.xmlSelladoField;
            }
            set {
                this.xmlSelladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] acuse {
            get {
                return this.acuseField;
            }
            set {
                this.acuseField = value;
            }
        }
        
        /// <remarks/>
        public wsItemCancelacionObj[] arrayFolios {
            get {
                return this.arrayFoliosField;
            }
            set {
                this.arrayFoliosField = value;
            }
        }
        
        /// <remarks/>
        public byte[][] arregloAcuse {
            get {
                return this.arregloAcuseField;
            }
            set {
                this.arregloAcuseField = value;
            }
        }
        
        /// <remarks/>
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaHoraTimbrado {
            get {
                return this.fechaHoraTimbradoField;
            }
            set {
                this.fechaHoraTimbradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraTimbradoSpecified {
            get {
                return this.fechaHoraTimbradoFieldSpecified;
            }
            set {
                this.fechaHoraTimbradoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fechaHoraTimbradoSpecified")]
        public bool fechaHoraTimbradoSpecified1 {
            get {
                return this.fechaHoraTimbradoSpecified1Field;
            }
            set {
                this.fechaHoraTimbradoSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public string folioUUID {
            get {
                return this.folioUUIDField;
            }
            set {
                this.folioUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
            }
        }
        
        /// <remarks/>
        public string selloDigitalEmisor {
            get {
                return this.selloDigitalEmisorField;
            }
            set {
                this.selloDigitalEmisorField = value;
            }
        }
        
        /// <remarks/>
        public string selloDigitalTimbreSAT {
            get {
                return this.selloDigitalTimbreSATField;
            }
            set {
                this.selloDigitalTimbreSATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfdi.ws2.facturehoy.certus.com/")]
    public partial class wsItemCancelacionObj {
        
        private int estatusField;
        
        private string uUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void sellarCompletedEventHandler(object sender, sellarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sellarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sellarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void timbrarCompletedEventHandler(object sender, timbrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void cancelarCompletedEventHandler(object sender, cancelarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void recuperarAcuseCompletedEventHandler(object sender, recuperarAcuseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class recuperarAcuseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal recuperarAcuseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RecuperarAcuseCancelacionCompletedEventHandler(object sender, RecuperarAcuseCancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarAcuseCancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarAcuseCancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591