//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.wsFechaHora {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsFechaHoraSoap", Namespace="http://tempuri.org/")]
    public partial class wsFechaHora : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecuperarFechaHoraActualOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsFechaHora() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.consumeWebservice_wsFechaHora_wsFechaHora;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecuperarFechaHoraActualCompletedEventHandler RecuperarFechaHoraActualCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperarFechaHoraActual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public respuesta RecuperarFechaHoraActual(string curCorreo, string password) {
            object[] results = this.Invoke("RecuperarFechaHoraActual", new object[] {
                        curCorreo,
                        password});
            return ((respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarFechaHoraActualAsync(string curCorreo, string password) {
            this.RecuperarFechaHoraActualAsync(curCorreo, password, null);
        }
        
        /// <remarks/>
        public void RecuperarFechaHoraActualAsync(string curCorreo, string password, object userState) {
            if ((this.RecuperarFechaHoraActualOperationCompleted == null)) {
                this.RecuperarFechaHoraActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarFechaHoraActualOperationCompleted);
            }
            this.InvokeAsync("RecuperarFechaHoraActual", new object[] {
                        curCorreo,
                        password}, this.RecuperarFechaHoraActualOperationCompleted, userState);
        }
        
        private void OnRecuperarFechaHoraActualOperationCompleted(object arg) {
            if ((this.RecuperarFechaHoraActualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarFechaHoraActualCompleted(this, new RecuperarFechaHoraActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class respuesta {
        
        private string erroresField;
        
        private string fechaActualField;
        
        private string horaActualField;
        
        private string fechaHoraActualField;
        
        /// <remarks/>
        public string errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
        
        /// <remarks/>
        public string fechaActual {
            get {
                return this.fechaActualField;
            }
            set {
                this.fechaActualField = value;
            }
        }
        
        /// <remarks/>
        public string horaActual {
            get {
                return this.horaActualField;
            }
            set {
                this.horaActualField = value;
            }
        }
        
        /// <remarks/>
        public string fechaHoraActual {
            get {
                return this.fechaHoraActualField;
            }
            set {
                this.fechaHoraActualField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RecuperarFechaHoraActualCompletedEventHandler(object sender, RecuperarFechaHoraActualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarFechaHoraActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarFechaHoraActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591