//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.WsPruebasPrimarioSIFEI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsTimbradoTextoPrimario33Soap", Namespace="www.facturaselectronicascfdi.com")]
    public partial class wsTimbradoTextoPrimario33 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TimbrarPorTextoPrimario33OperationCompleted;
        
        private System.Threading.SendOrPostCallback SellarTimbrarPorTextoPrimario33OperationCompleted;
        
        private System.Threading.SendOrPostCallback TimbrarPorLoteTextoPrimario33OperationCompleted;
        
        private System.Threading.SendOrPostCallback ComandoTimbradoLoteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsTimbradoTextoPrimario33() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.consumeWebservice_WsPruebasPrimarioSIFEI_wsTimbradoTextoPrimario33;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TimbrarPorTextoPrimario33CompletedEventHandler TimbrarPorTextoPrimario33Completed;
        
        /// <remarks/>
        public event SellarTimbrarPorTextoPrimario33CompletedEventHandler SellarTimbrarPorTextoPrimario33Completed;
        
        /// <remarks/>
        public event TimbrarPorLoteTextoPrimario33CompletedEventHandler TimbrarPorLoteTextoPrimario33Completed;
        
        /// <remarks/>
        public event ComandoTimbradoLoteCompletedEventHandler ComandoTimbradoLoteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.facturaselectronicascfdi.com/TimbrarPorTextoPrimario33", RequestNamespace="www.facturaselectronicascfdi.com", ResponseNamespace="www.facturaselectronicascfdi.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultadoprimario33 TimbrarPorTextoPrimario33(string correo, string pass, string Proceso, string contenidoArchivo) {
            object[] results = this.Invoke("TimbrarPorTextoPrimario33", new object[] {
                        correo,
                        pass,
                        Proceso,
                        contenidoArchivo});
            return ((resultadoprimario33)(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarPorTextoPrimario33Async(string correo, string pass, string Proceso, string contenidoArchivo) {
            this.TimbrarPorTextoPrimario33Async(correo, pass, Proceso, contenidoArchivo, null);
        }
        
        /// <remarks/>
        public void TimbrarPorTextoPrimario33Async(string correo, string pass, string Proceso, string contenidoArchivo, object userState) {
            if ((this.TimbrarPorTextoPrimario33OperationCompleted == null)) {
                this.TimbrarPorTextoPrimario33OperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarPorTextoPrimario33OperationCompleted);
            }
            this.InvokeAsync("TimbrarPorTextoPrimario33", new object[] {
                        correo,
                        pass,
                        Proceso,
                        contenidoArchivo}, this.TimbrarPorTextoPrimario33OperationCompleted, userState);
        }
        
        private void OnTimbrarPorTextoPrimario33OperationCompleted(object arg) {
            if ((this.TimbrarPorTextoPrimario33Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarPorTextoPrimario33Completed(this, new TimbrarPorTextoPrimario33CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.facturaselectronicascfdi.com/SellarTimbrarPorTextoPrimario33", RequestNamespace="www.facturaselectronicascfdi.com", ResponseNamespace="www.facturaselectronicascfdi.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultadoprimario33 SellarTimbrarPorTextoPrimario33(string correo, string pass, string Proceso, string contenidoArchivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] cerFile, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] keyFile, string passCer) {
            object[] results = this.Invoke("SellarTimbrarPorTextoPrimario33", new object[] {
                        correo,
                        pass,
                        Proceso,
                        contenidoArchivo,
                        cerFile,
                        keyFile,
                        passCer});
            return ((resultadoprimario33)(results[0]));
        }
        
        /// <remarks/>
        public void SellarTimbrarPorTextoPrimario33Async(string correo, string pass, string Proceso, string contenidoArchivo, byte[] cerFile, byte[] keyFile, string passCer) {
            this.SellarTimbrarPorTextoPrimario33Async(correo, pass, Proceso, contenidoArchivo, cerFile, keyFile, passCer, null);
        }
        
        /// <remarks/>
        public void SellarTimbrarPorTextoPrimario33Async(string correo, string pass, string Proceso, string contenidoArchivo, byte[] cerFile, byte[] keyFile, string passCer, object userState) {
            if ((this.SellarTimbrarPorTextoPrimario33OperationCompleted == null)) {
                this.SellarTimbrarPorTextoPrimario33OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSellarTimbrarPorTextoPrimario33OperationCompleted);
            }
            this.InvokeAsync("SellarTimbrarPorTextoPrimario33", new object[] {
                        correo,
                        pass,
                        Proceso,
                        contenidoArchivo,
                        cerFile,
                        keyFile,
                        passCer}, this.SellarTimbrarPorTextoPrimario33OperationCompleted, userState);
        }
        
        private void OnSellarTimbrarPorTextoPrimario33OperationCompleted(object arg) {
            if ((this.SellarTimbrarPorTextoPrimario33Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SellarTimbrarPorTextoPrimario33Completed(this, new SellarTimbrarPorTextoPrimario33CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.facturaselectronicascfdi.com/TimbrarPorLoteTextoPrimario33", RequestNamespace="www.facturaselectronicascfdi.com", ResponseNamespace="www.facturaselectronicascfdi.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultadoloteprimario33 TimbrarPorLoteTextoPrimario33(string correo, string pass, string Proceso, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Lote) {
            object[] results = this.Invoke("TimbrarPorLoteTextoPrimario33", new object[] {
                        correo,
                        pass,
                        Proceso,
                        Lote});
            return ((resultadoloteprimario33)(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarPorLoteTextoPrimario33Async(string correo, string pass, string Proceso, byte[] Lote) {
            this.TimbrarPorLoteTextoPrimario33Async(correo, pass, Proceso, Lote, null);
        }
        
        /// <remarks/>
        public void TimbrarPorLoteTextoPrimario33Async(string correo, string pass, string Proceso, byte[] Lote, object userState) {
            if ((this.TimbrarPorLoteTextoPrimario33OperationCompleted == null)) {
                this.TimbrarPorLoteTextoPrimario33OperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarPorLoteTextoPrimario33OperationCompleted);
            }
            this.InvokeAsync("TimbrarPorLoteTextoPrimario33", new object[] {
                        correo,
                        pass,
                        Proceso,
                        Lote}, this.TimbrarPorLoteTextoPrimario33OperationCompleted, userState);
        }
        
        private void OnTimbrarPorLoteTextoPrimario33OperationCompleted(object arg) {
            if ((this.TimbrarPorLoteTextoPrimario33Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarPorLoteTextoPrimario33Completed(this, new TimbrarPorLoteTextoPrimario33CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.facturaselectronicascfdi.com/ComandoTimbradoLote", RequestNamespace="www.facturaselectronicascfdi.com", ResponseNamespace="www.facturaselectronicascfdi.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultadoloteprimario33 ComandoTimbradoLote(string correo, string pass, string Commando, string PID) {
            object[] results = this.Invoke("ComandoTimbradoLote", new object[] {
                        correo,
                        pass,
                        Commando,
                        PID});
            return ((resultadoloteprimario33)(results[0]));
        }
        
        /// <remarks/>
        public void ComandoTimbradoLoteAsync(string correo, string pass, string Commando, string PID) {
            this.ComandoTimbradoLoteAsync(correo, pass, Commando, PID, null);
        }
        
        /// <remarks/>
        public void ComandoTimbradoLoteAsync(string correo, string pass, string Commando, string PID, object userState) {
            if ((this.ComandoTimbradoLoteOperationCompleted == null)) {
                this.ComandoTimbradoLoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnComandoTimbradoLoteOperationCompleted);
            }
            this.InvokeAsync("ComandoTimbradoLote", new object[] {
                        correo,
                        pass,
                        Commando,
                        PID}, this.ComandoTimbradoLoteOperationCompleted, userState);
        }
        
        private void OnComandoTimbradoLoteOperationCompleted(object arg) {
            if ((this.ComandoTimbradoLoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ComandoTimbradoLoteCompleted(this, new ComandoTimbradoLoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.facturaselectronicascfdi.com")]
    public partial class resultadoprimario33 {
        
        private string selloField;
        
        private string erroresField;
        
        private byte[] xmlSelladoField;
        
        private byte[] acuseField;
        
        private byte[][] arregloAcuseField;
        
        private string cadenaOriginalField;
        
        private System.DateTime fechaHoraTimbradoField;
        
        private bool fechaHoraTimbradoFieldSpecified;
        
        private bool fechaHoraTimbradoSpecified1Field;
        
        private string folioUUIDField;
        
        private byte[] pDFField;
        
        private string selloDigitalEmisorField;
        
        private string selloDigitalTimbreSATField;
        
        private byte[] xMLField;
        
        private int idTimbradoField;
        
        /// <remarks/>
        public string sello {
            get {
                return this.selloField;
            }
            set {
                this.selloField = value;
            }
        }
        
        /// <remarks/>
        public string errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] xmlSellado {
            get {
                return this.xmlSelladoField;
            }
            set {
                this.xmlSelladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] acuse {
            get {
                return this.acuseField;
            }
            set {
                this.acuseField = value;
            }
        }
        
        /// <remarks/>
        public byte[][] arregloAcuse {
            get {
                return this.arregloAcuseField;
            }
            set {
                this.arregloAcuseField = value;
            }
        }
        
        /// <remarks/>
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaHoraTimbrado {
            get {
                return this.fechaHoraTimbradoField;
            }
            set {
                this.fechaHoraTimbradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraTimbradoSpecified {
            get {
                return this.fechaHoraTimbradoFieldSpecified;
            }
            set {
                this.fechaHoraTimbradoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fechaHoraTimbradoSpecified")]
        public bool fechaHoraTimbradoSpecified1 {
            get {
                return this.fechaHoraTimbradoSpecified1Field;
            }
            set {
                this.fechaHoraTimbradoSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public string folioUUID {
            get {
                return this.folioUUIDField;
            }
            set {
                this.folioUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
            }
        }
        
        /// <remarks/>
        public string selloDigitalEmisor {
            get {
                return this.selloDigitalEmisorField;
            }
            set {
                this.selloDigitalEmisorField = value;
            }
        }
        
        /// <remarks/>
        public string selloDigitalTimbreSAT {
            get {
                return this.selloDigitalTimbreSATField;
            }
            set {
                this.selloDigitalTimbreSATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
        
        /// <remarks/>
        public int IdTimbrado {
            get {
                return this.idTimbradoField;
            }
            set {
                this.idTimbradoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.facturaselectronicascfdi.com")]
    public partial class resultadoloteprimario33 {
        
        private string erroresField;
        
        private string statusField;
        
        private string infoTimbradoField;
        
        private string pIDField;
        
        private byte[] archivoField;
        
        /// <remarks/>
        public string Errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string InfoTimbrado {
            get {
                return this.infoTimbradoField;
            }
            set {
                this.infoTimbradoField = value;
            }
        }
        
        /// <remarks/>
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void TimbrarPorTextoPrimario33CompletedEventHandler(object sender, TimbrarPorTextoPrimario33CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbrarPorTextoPrimario33CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbrarPorTextoPrimario33CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultadoprimario33 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultadoprimario33)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void SellarTimbrarPorTextoPrimario33CompletedEventHandler(object sender, SellarTimbrarPorTextoPrimario33CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SellarTimbrarPorTextoPrimario33CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SellarTimbrarPorTextoPrimario33CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultadoprimario33 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultadoprimario33)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void TimbrarPorLoteTextoPrimario33CompletedEventHandler(object sender, TimbrarPorLoteTextoPrimario33CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbrarPorLoteTextoPrimario33CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbrarPorLoteTextoPrimario33CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultadoloteprimario33 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultadoloteprimario33)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void ComandoTimbradoLoteCompletedEventHandler(object sender, ComandoTimbradoLoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComandoTimbradoLoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ComandoTimbradoLoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultadoloteprimario33 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultadoloteprimario33)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591